ALTER TABLE signals
    ADD COLUMN IF NOT EXISTS vol_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS mom_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS volat_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS price_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS candle_kategori VARCHAR(20),
    ADD COLUMN IF NOT EXISTS all_up BOOLEAN;
