-- Migration: Signal tablosuna auto-increment ID kolonu ekleme (eski primary key korunur)
-- Date: 2025-09-17
-- Description: ID kolonunu auto-increment unique yapar, eski primary key (symbol+timestamp) korunur

-- 1. ID kolonunu auto-increment yap (PostgreSQL SERIAL)
ALTER TABLE signals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. ID kolonu için unique constraint ekle
ALTER TABLE signals ADD CONSTRAINT signals_id_unique UNIQUE (id);

-- 3. Performans için index'ler ekle
CREATE INDEX IF NOT EXISTS idx_signals_id ON signals (id);
CREATE INDEX IF NOT EXISTS idx_signals_symbol_interval_status ON signals (symbol, interval, status);
CREATE INDEX IF NOT EXISTS idx_signals_indicators_status ON signals (indicators, status);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp_status ON signals (timestamp, status);

-- 4. Mevcut NULL id'leri düzelt (eğer varsa)
UPDATE signals SET id = nextval(pg_get_serial_sequence('signals', 'id')) WHERE id IS NULL;
